In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import ast

with open('names.txt', 'r') as f:
    mylist = ast.literal_eval(f.read())

In [3]:
with open('favourites_count.txt', 'r') as f:
    my_favourites = ast.literal_eval(f.read())

In [4]:
with open('default_profile.txt', 'r') as f:
    default_profile = ast.literal_eval(f.read())

In [5]:
with open('default_profile_image.txt', 'r') as f:
    default_profile_image = ast.literal_eval(f.read())

In [6]:
with open('geo_enabled.txt', 'r') as f:
    geo_enabled = ast.literal_eval(f.read())
geo_enabled

[True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 ...]

In [7]:
users_2020_15 = pd.DataFrame(
    {'screen_name': mylist,
     'favourites_count': my_favourites,
     'default_profile': default_profile,
     "default_profile_image":default_profile_image,
     'geo_enabled':geo_enabled
    })

In [8]:
users_2020_15

,screen_name,favourites_count,default_profile,default_profile_image,geo_enabled
0,HavenFaithc,39217,False,False,True
1,BotafogoBoy,257,False,False,False
2,MagnusDanger,8522,False,False,True
3,kipjmooney,779451,False,False,True
4,BkiIhi,0,True,False,False
...,...,...,...,...,...
14564,vampirebimbo,25,True,False,False
14565,Claddagh_J,10358,True,False,False
14566,JulianJ30229843,45,True,False,False
14567,keishajo9,134831,False,False,False
14568,WoodstockQuotes,3,True,False,False

In [9]:
df=pd.read_csv('tweets2020_ML.csv')
df

,id_str,created_at_1,full_text,lang,in_reply_to_status_id_str,in_reply_to_user_id,entities.hashtags,entities.media,entities.symbols,entities.urls,...,average_tweets_per_day,avg_daily_followers,avg_daily_friends,friends_log,followers_log,avg_daily_tweets_log,network,tweet_to_followers,follower_acq_rate,friends_acq_rate
0,1344795435672678400,2020-12-31 23:59:51+00:00,Feel like my last tweet of 2020 needs to be a ...,en,0.000000e+00,0.000000e+00,"[{'indices': [95, 116], 'text': 'JusticeForJoh...",0,[],[],...,7.004456,0.418,0.271,6.057,6.488,2.080,39.298,60.375,0.349,0.240
1,1344795283352215553,2020-12-31 23:59:15+00:00,@ZackSnyder Isn’t that abuser and liar in this...,en,1.344704e+18,1.776831e+07,[],"[{'original_info': {'width': 750, 'focus_rects...",[],[],...,33.212903,0.884,0.265,3.738,4.927,3.533,18.417,42.111,0.633,0.235
2,1344795202389741568,2020-12-31 23:58:55+00:00,Happy New Year to everyone....except Amber Hea...,en,0.000000e+00,0.000000e+00,[],0,[],[],...,0.446602,0.122,0.232,6.913,6.271,0.369,43.351,47.451,0.115,0.209
3,1344795194240233473,2020-12-31 23:58:54+00:00,It’s time let’s ring in 2021 with Karma coming...,en,0.000000e+00,0.000000e+00,[],0,[],[],...,5.410611,0.038,0.039,4.477,4.454,1.858,19.941,41.889,0.037,0.038
4,1344795047926108162,2020-12-31 23:58:19+00:00,Passando pra desejar um 2021 maravilhoso pra t...,pt,0.000000e+00,0.000000e+00,"[{'indices': [57, 78], 'text': 'JusticeForJohn...",0,[],[],...,3.695913,0.641,0.549,7.352,7.506,1.547,55.184,69.492,0.495,0.438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196246,1212288255229644800,2020-01-01 08:23:37+00:00,If anyone knows that caring about skin care an...,en,0.000000e+00,0.000000e+00,[],0,[],[{'display_url': 'glamourmagazine.co.uk/articl...,...,46.079898,121.906,1.231,8.478,13.073,3.852,110.833,158.192,4.811,0.803
196247,1212276399240814592,2020-01-01 07:36:31+00:00,Amber heard me throw up omg,en,0.000000e+00,0.000000e+00,[],0,[],[],...,27.512592,0.246,0.195,5.919,6.151,3.350,36.408,66.841,0.220,0.178
196248,1212221353627201538,2020-01-01 03:57:47+00:00,51. Amber Heard https://t.co/YNJt2JISM6,en,1.212221e+18,1.117565e+18,[],"[{'original_info': {'width': 683, 'focus_rects...",[],[],...,195.509579,143.648,2.866,6.619,10.532,5.281,69.711,114.167,4.974,1.352
196249,1212213234108977155,2020-01-01 03:25:31+00:00,"#TuesdayNightLineup: \n ""Aquaman"" starring ...",en,0.000000e+00,0.000000e+00,"[{'indices': [0, 19], 'text': 'TuesdayNightLin...",0,[],[],...,66.647672,0.203,0.045,5.170,6.685,4.214,34.561,83.398,0.185,0.044
196250,1212188781081776129,2020-01-01 01:48:21+00:00,@discosaIIy Con amber heard,en,1.212188e+18,3.019578e+09,[],0,[],[],...,158.686217,0.597,0.644,6.087,6.011,5.073,36.589,69.682,0.468,0.497

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196251 entries, 0 to 196250
Data columns (total 51 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   id_str                                   196251 non-null  int64
 1   created_at_1                             196251 non-null  object
 2   full_text                                196251 non-null  object
 3   lang                                     196251 non-null  object
 4   in_reply_to_status_id_str                196251 non-null  float64
 5   in_reply_to_user_id                      196251 non-null  float64
 6   entities.hashtags                        196251 non-null  object
 7   entities.media                           196251 non-null  object
 8   entities.symbols                         196251 non-null  object
 9   entities.urls                            196251 non-null  object
 10  entities.user_mentions                   196251 non-null  object
 11  source                                   196251 non-null  object
 12  quoted_status.id_str                     196251 non-null  float64
 13  quoted_status.created_at                 196251 non-null  object
 14  quoted_status.full_text                  196251 non-null  object
 15  quoted_status.lang                       196251 non-null  object
 16  quoted_status.in_reply_to_status_id_str  196251 non-null  float64
 17  quoted_status.in_reply_to_user_id        196251 non-null  float64
 18  quoted_status.entities.hashtags          196251 non-null  object
 19  quoted_status.entities.media             196251 non-null  object
 20  quoted_status.entities.symbols           196251 non-null  object
 21  quoted_status.entities.urls              196251 non-null  object
 22  quoted_status.entities.user_mentions     196251 non-null  object
 23  quoted_status.user.id_str                196251 non-null  float64
 24  quoted_status.source                     196251 non-null  object
 25  user.id_str                              196251 non-null  float64
 26  created_at                               196251 non-null  object
 27  user.description                         196251 non-null  object
 28  followers_count                          196251 non-null  int64
 29  friends_count                            196251 non-null  int64
 30  user.lang                                196251 non-null  float64
 31  location                                 196251 non-null  object
 32  name                                     196251 non-null  object
 33  screen_name                              196251 non-null  object
 34  profile_banner_url                       196251 non-null  object
 35  profile_image_url                        196251 non-null  object
 36  statuses_count                           196251 non-null  int64
 37  url                                      196251 non-null  object
 38  verified                                 196251 non-null  int64
 39  hour_created                             196251 non-null  int64
 40  account_age_days                         196251 non-null  int64
 41  average_tweets_per_day                   196251 non-null  float64
 42  avg_daily_followers                      195821 non-null  float64
 43  avg_daily_friends                        196095 non-null  float64
 44  friends_log                              196251 non-null  float64
 45  followers_log                            196251 non-null  float64
 46  avg_daily_tweets_log                     196251 non-null  float64
 47  network                                  196251 non-null  float64
 48  tweet_to_followers                       196251 non-null  float64
 49  follower_acq_rate                        195821 non-null  float64
 50  friends_acq_rate                         196095 non-null  float64
dtypes: float64(18), int64(7), object(26)
memory usage: 76.4+ MB

In [11]:
df_full=pd.merge(users_2020_15,df,how='inner',on='screen_name')

In [12]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14546 entries, 0 to 14545
Data columns (total 55 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   screen_name                              14546 non-null  object
 1   favourites_count                         14546 non-null  int64
 2   default_profile                          14546 non-null  bool
 3   default_profile_image                    14546 non-null  bool
 4   geo_enabled                              14546 non-null  bool
 5   id_str                                   14546 non-null  int64
 6   created_at_1                             14546 non-null  object
 7   full_text                                14546 non-null  object
 8   lang                                     14546 non-null  object
 9   in_reply_to_status_id_str                14546 non-null  float64
 10  in_reply_to_user_id                      14546 non-null  float64
 11  entities.hashtags                        14546 non-null  object
 12  entities.media                           14546 non-null  object
 13  entities.symbols                         14546 non-null  object
 14  entities.urls                            14546 non-null  object
 15  entities.user_mentions                   14546 non-null  object
 16  source                                   14546 non-null  object
 17  quoted_status.id_str                     14546 non-null  float64
 18  quoted_status.created_at                 14546 non-null  object
 19  quoted_status.full_text                  14546 non-null  object
 20  quoted_status.lang                       14546 non-null  object
 21  quoted_status.in_reply_to_status_id_str  14546 non-null  float64
 22  quoted_status.in_reply_to_user_id        14546 non-null  float64
 23  quoted_status.entities.hashtags          14546 non-null  object
 24  quoted_status.entities.media             14546 non-null  object
 25  quoted_status.entities.symbols           14546 non-null  object
 26  quoted_status.entities.urls              14546 non-null  object
 27  quoted_status.entities.user_mentions     14546 non-null  object
 28  quoted_status.user.id_str                14546 non-null  float64
 29  quoted_status.source                     14546 non-null  object
 30  user.id_str                              14546 non-null  float64
 31  created_at                               14546 non-null  object
 32  user.description                         14546 non-null  object
 33  followers_count                          14546 non-null  int64
 34  friends_count                            14546 non-null  int64
 35  user.lang                                14546 non-null  float64
 36  location                                 14546 non-null  object
 37  name                                     14546 non-null  object
 38  profile_banner_url                       14546 non-null  object
 39  profile_image_url                        14546 non-null  object
 40  statuses_count                           14546 non-null  int64
 41  url                                      14546 non-null  object
 42  verified                                 14546 non-null  int64
 43  hour_created                             14546 non-null  int64
 44  account_age_days                         14546 non-null  int64
 45  average_tweets_per_day                   14546 non-null  float64
 46  avg_daily_followers                      14519 non-null  float64
 47  avg_daily_friends                        14535 non-null  float64
 48  friends_log                              14546 non-null  float64
 49  followers_log                            14546 non-null  float64
 50  avg_daily_tweets_log                     14546 non-null  float64
 51  network                                  14546 non-null  float64
 52  tweet_to_followers                       14546 non-null  float64
 53  follower_acq_rate                        14519 non-null  float64
 54  friends_acq_rate                         14535 non-null  float64
dtypes: bool(3), float64(18), int64(8), object(26)
memory usage: 5.9+ MB

In [19]:
df_full['avg_daily_favorites'] = np.round((df_full['favourites_count'] / df_full['account_age_days']), 3)

In [20]:
df_full['favs_log'] = np.round(np.log(1 + df_full['favourites_count']), 3)

In [21]:
df_full['favs_rate'] = np.round(np.log(1 + (df_full['friends_count'] / df_full['account_age_days'])), 3)

In [25]:
df_full.fillna(0,inplace=True)
df_full['default_profile'] = df_full['default_profile'].astype(int)
df_full['default_profile'] = df_full['default_profile'].astype(int)
df_full['default_profile_image'] = df_full['default_profile_image'].astype(int)
df_full['geo_enabled'] = df_full['geo_enabled'].astype(int)
df_full['verified'] = df_full['verified'].astype(int)
df_full['created_at_1']=pd.to_datetime(df_full['created_at_1'])
df_full['created_at']=pd.to_datetime(df_full['created_at'])

In [26]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14546 entries, 0 to 14545
Data columns (total 58 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   screen_name                              14546 non-null  object
 1   favourites_count                         14546 non-null  int64
 2   default_profile                          14546 non-null  int32
 3   default_profile_image                    14546 non-null  int32
 4   geo_enabled                              14546 non-null  int32
 5   id_str                                   14546 non-null  int64
 6   created_at_1                             14546 non-null  datetime64[ns, UTC]
 7   full_text                                14546 non-null  object
 8   lang                                     14546 non-null  object
 9   in_reply_to_status_id_str                14546 non-null  float64
 10  in_reply_to_user_id                      14546 non-null  float64
 11  entities.hashtags                        14546 non-null  object
 12  entities.media                           14546 non-null  object
 13  entities.symbols                         14546 non-null  object
 14  entities.urls                            14546 non-null  object
 15  entities.user_mentions                   14546 non-null  object
 16  source                                   14546 non-null  object
 17  quoted_status.id_str                     14546 non-null  float64
 18  quoted_status.created_at                 14546 non-null  object
 19  quoted_status.full_text                  14546 non-null  object
 20  quoted_status.lang                       14546 non-null  object
 21  quoted_status.in_reply_to_status_id_str  14546 non-null  float64
 22  quoted_status.in_reply_to_user_id        14546 non-null  float64
 23  quoted_status.entities.hashtags          14546 non-null  object
 24  quoted_status.entities.media             14546 non-null  object
 25  quoted_status.entities.symbols           14546 non-null  object
 26  quoted_status.entities.urls              14546 non-null  object
 27  quoted_status.entities.user_mentions     14546 non-null  object
 28  quoted_status.user.id_str                14546 non-null  float64
 29  quoted_status.source                     14546 non-null  object
 30  user.id_str                              14546 non-null  float64
 31  created_at                               14546 non-null  datetime64[ns, UTC]
 32  user.description                         14546 non-null  object
 33  followers_count                          14546 non-null  int64
 34  friends_count                            14546 non-null  int64
 35  user.lang                                14546 non-null  float64
 36  location                                 14546 non-null  object
 37  name                                     14546 non-null  object
 38  profile_banner_url                       14546 non-null  object
 39  profile_image_url                        14546 non-null  object
 40  statuses_count                           14546 non-null  int64
 41  url                                      14546 non-null  object
 42  verified                                 14546 non-null  int32
 43  hour_created                             14546 non-null  int64
 44  account_age_days                         14546 non-null  int64
 45  average_tweets_per_day                   14546 non-null  float64
 46  avg_daily_followers                      14546 non-null  float64
 47  avg_daily_friends                        14546 non-null  float64
 48  friends_log                              14546 non-null  float64
 49  followers_log                            14546 non-null  float64
 50  avg_daily_tweets_log                     14546 non-null  float64
 51  network                                  14546 non-null  float64
 52  tweet_to_followers                       14546 non-null  float64
 53  follower_acq_rate                        14546 non-null  float64
 54  friends_acq_rate                         14546 non-null  float64
 55  avg_daily_favorites                      14546 non-null  float64
 56  favs_log                                 14546 non-null  float64
 57  favs_rate                                14546 non-null  float64
dtypes: datetime64[ns, UTC](2), float64(21), int32(4), int64(7), object(24)
memory usage: 6.3+ MB

In [27]:
list(set(mylist) - set(s))

['cardiZ14',
 'OnlyRons',
 'cherry_raindrop',
 'AANDHRAWAALA',
 'MahimaInduwara4',
 'muhammadkolo_',
 'Andrades19',
 'IamLeeNelson',
 '_yougotnojam_',
 'arientradutora',
 'BonganiMnisi1',
 'harjung_melina',
 'ughbangt7n',
 'nayie_',
 'onlynarathar',
 'anifyel',
 'Uilegal',
 'nan',
 'MiiresDilley',
 'AveryScarlet1',
 'XYZ_stan',
 'spectatorUSA',
 'trafickeer']

In [32]:
features = ['verified', 
            'hour_created',
            'geo_enabled', 
            'default_profile', 
            'default_profile_image', 
            'favourites_count', 
            'followers_count', 
            'friends_count', 
            'statuses_count', 
            'average_tweets_per_day',
            'network', 
            'tweet_to_followers', 
            'follower_acq_rate', 
            'friends_acq_rate', 
           ]

X = df_full[features]

In [29]:
import pickle

In [30]:
with open('model.pickle', 'rb') as to_write:
    mod = pickle.load(to_write)

In [36]:
z=mod.predict(X)

In [38]:
type(z)

numpy.ndarray

In [39]:
bots=z.tolist()

In [44]:
bots_2020 = pd.DataFrame(
    {'screen_name': s,
     'bots':bots
    })

In [45]:
bots_2020

           screen_name  bots
0          HavenFaithc     0
1          BotafogoBoy     0
2         MagnusDanger     0
3           kipjmooney     0
4               BkiIhi     1
...                ...   ...
14541     vampirebimbo     1
14542       Claddagh_J     1
14543  JulianJ30229843     1
14544        keishajo9     0
14545  WoodstockQuotes     1

[14546 rows x 2 columns]

In [48]:
bots_2020[bots_2020['bots']==1].sum()

screen_name    BkiIhiAppituBlogGold__MoneyCaliBDiamondMotionP...
bots                                                        4556
dtype: object